### PR TITLE
Fixed: some entity names lead to errors on save

### PR DESCRIPTION
**Pull request by cblech**
#3tmdjjf

### CODE REVIEW

**Comment by MGH-Automator** [comment]
Task linked: [CU-3tmdjjf Fix bug: when entity name contains some special characters it will throw an exception](https://app.clickup.com/t/3tmdjjf)

**Review by tcdrop — COMMENTED** [review]
Another approach would be to use a whitelist. That way we don't run into any problems in case we missed some characters. We then only allow the user to type in things like a-z, A-Z, 0-9, _, # etc.

**Comment by cblech** [comment]
In the whitelist approach we have a much higher potential to miss characters. For example all Chinese characters.

On the other hand, characters that are **not** allowed are well documented: https://en.wikipedia.org/wiki/Filename

**Review by MichiGandi — APPROVED** [review]
tppi toppi

**Pull request merged**
